### ISSUE TITLE
Gem co-authorship

### ISSUE THREAD

**Issue by julik** [guerilla-di/edl#9]
@phigrofi can you please let me know your email address you use on rubygems.org, so that I can add you to the authors? You will then be able to push releases.

**Comment by phigrofi** [comment]
its philipp.grosselfinger@gmail.com.
Thanks again.

**Comment by julik** [comment]
Not quite - you actually need to register on rubygems for this to work.

**Comment by phigrofi** [comment]
Ah ok, now!

**Comment by julik** [comment]
I've added you. Now you can bump the version and release (`bundle exec rake release`)

**Comment by phigrofi** [comment]
Great! Thanks!

Am 07.06.2017 4:36 nachm. schrieb "Julik Tarkhanov" <
notifications@github.com>:
